export const routes = {
  home: "/",
  annoucements: "/discussion/announcements",
  suggestions: "/discussion/suggestions",
  requests: "/discussion/requests",
  novel: "/novel/",
  chapter: "/chapter/",
  tag: "/tag/",
  category: "/category/",
  login: "/user/login/",
  signup: "/user/signup/",
  readingList: "/user/reading-list/",
  search: "/search/",
  profile: "/user/profile/",
  profileView: "/user/profile/view",
  bookmark: "/user/profile/bookmark",
  settings: "/user/profile/settings",
  preferences: "/user/profile/preferences",
  privacyPolicy: "/about/privacy-policy/",
  tags: "/show_all/tags",
  categories: "/show_all/categories",
};
